Documentation [Click here](https://docs.google.com/document/d/1UCBOAd6hXNAGJS5-_IgUxvcjoBvlQqxFVOb4L-v9MEw/edit)

In [1]:
import numpy as np

In [13]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9],[45,44,46]])
a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [45, 44, 46]])

In [8]:
a3=np.array([],dtype="int")
a3=np.append(a3,int(input()))

11


In [9]:
a3

array([11])

# slicing

In [16]:
print(a1[2:,0])

[ 7 45]


In [19]:
print(a1[0,0:2])

[1 2]


In [26]:
print(a1[0::3,:])

[[ 1  2  3]
 [45 44 46]]


In [27]:
for row in a1:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[45 44 46]


In [28]:
l1=[[1,2],[3,4]]
for i in l1:
    print(i)

[1, 2]
[3, 4]


In [29]:
np.array(a1.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 45, 44, 46])

# Indexing with boolean array

In [32]:
arr1=np.arange(1,21).reshape(5,4)

In [33]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [38]:
result=(arr1%2==0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [40]:
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# Appending Array

In [42]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)


In [43]:
arr2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [44]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
# vertical stacking
print(np.vstack((arr1,arr2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [49]:
print(np.hstack((arr1,arr2)))

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


## Attributes
1. size
2. itemsize
3. dtype
4. ndim
5. shape

In [51]:
arr=np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [52]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.shape)

10
4
int32
(2, 5)


## Functions
1. zeros
2. ones
3. full
4. eye
5. linspace
6. arange
7. reshape
8. ravel

In [55]:
b=np.zeros((2,3),dtype="int32")
b

array([[0, 0, 0],
       [0, 0, 0]])

In [56]:
o=np.ones((2,3))

In [57]:
o

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
f=np.full((2,2),"aj")
f

array([['aj', 'aj'],
       ['aj', 'aj']], dtype='<U2')

In [60]:
#eye()
e=np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [61]:
#linspace()-->linear spacing elements
lin=np.linspace(1,11,5)
lin

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [62]:
b=np.arange(1,11,2)

In [63]:
b

array([1, 3, 5, 7, 9])

In [68]:
#ravel()
print(np.array(a1.flat))
print(a1.ravel())

[ 1  2  3  4  5  6  7  8  9 45 44 46]
[ 1  2  3  4  5  6  7  8  9 45 44 46]


In [73]:
print(a1.sum())
print(a1.sum(axis=1))#sum of row elements
print(a1.sum(axis=0))#sum of col elements

180
[  6  15  24 135]
[57 59 64]


In [75]:
print(a1.min())
print(a1.max())

1
46


In [76]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [6.70820393, 6.63324958, 6.78232998]])

In [77]:
np.mean(a1)
np.median(a1)

6.5

In [78]:
np.mean(a1)

15.0

In [79]:
np.std(a1)

17.46902019767184

## Mathematical Operations: +,-,*,/,%

In [83]:
x=np.array([[1,2],[3,4],[5,6]])
y=np.array([[55,2],[33,1],[21,16]])

In [84]:
x/y

array([[0.01818182, 1.        ],
       [0.09090909, 4.        ],
       [0.23809524, 0.375     ]])

In [85]:
x+y

array([[56,  4],
       [36,  5],
       [26, 22]])

In [86]:
x*y

array([[ 55,   4],
       [ 99,   4],
       [105,  96]])

In [89]:
x%y

array([[1, 0],
       [3, 0],
       [5, 6]], dtype=int32)

# dot()-Matrix Multiplication


In [88]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [91]:
#Transpose of matrix
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Applying user defined-function

In [92]:
list1=list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [93]:
res=[x/(x+1) for x in list1]
res

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [94]:
f=np.vectorize(lambda x: x/(x+1))
f(arr1)

array([[0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.85714286],
       [0.875     , 0.88888889, 0.9       ]])