 Documenation Image processing [click here](https://docs.google.com/document/d/1t0H64vkTHa_PqceXz-DHDZI2ad2QJpaHjNudoWxI3J0/edit)
 
 Documentation of Session [click here](https://docs.google.com/document/d/1gQjR0OaeopGFyyxAV6kKZiZf1kMNeiAfHx6hXtCaGv0/edit)

In [5]:
from numpy import random
print(random.randint(1,100))#random integer int he given range
print(random.rand())#float number 0-1

90
0.2559570396876152


In [7]:
#creating  n-dimensional array with random integer values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[64 48 56]
[[ 3 31 40 50]
 [96 61 79 13]
 [45 31 43 61]]
[[[67 53]
  [98 35]
  [ 0  4]
  [42 13]]

 [[48 45]
  [41 52]
  [37 17]
  [65 54]]

 [[68 63]
  [69 33]
  [79  2]
  [19 86]]]


In [9]:
#creating n-dimensional array with random floating-point values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.26524103337982696
[0.29686806 0.74839195 0.73986933]
[[0.04042113 0.83579363 0.42456382]
 [0.88544206 0.88798144 0.75092472]]


In [11]:
a=random.randint(100,size=(3,2)).ravel()
a

array([81, 97,  6, 74, 58, 84])

In [12]:
random.choice(a)

97

In [20]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(4,4))

TypeError: choice() got an unexpected keyword argument 'size'

# pandas
1. Data manipulation,analysis and cleaning
2. Tabular data,Unlabelled data

## creating a DataFrame
1. using 2 dictionaries

In [30]:
import numpy as np
import pandas as pd
d1={'a':1,'b':2,'c':3,'d':4,'e':5}
d2={'a':5,'b':6,'c':7,'d':8,'e':9}
data={"First":d1,"Second":d2}
df=pd.DataFrame(data,dtype="int32")
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [32]:
#simple dictionary --> DataFrame
d1={"name":["a","b","v"],"address":["c","d","e"]}
df1=pd.DataFrame(d1)
df1

name address
0    a       c
1    b       d
2    v       e

In [33]:
#Using Series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([1.1,2.1,3.1,4.1,5.1,6.1,7.1,8.1,9.1,10.1])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={"col1":s1,"col2":s2,"col3":s3}
df2=pd.DataFrame(data)
df2

col1  col2 col3
0     1   1.1    a
1     2   2.1    b
2     3   3.1    c
3     4   4.1    d
4     5   5.1    e
5     6   6.1    f
6     7   7.1    g
7     8   8.1    h
8     9   9.1    i
9    10  10.1    j

## Selecting the data from the DataFrame
1. loc
2. iloc

In [34]:
df2["col2"]

0     1.1
1     2.1
2     3.1
3     4.1
4     5.1
5     6.1
6     7.1
7     8.1
8     9.1
9    10.1
Name: col2, dtype: float64

In [36]:
df2[["col2","col3"]]

col2 col3
0   1.1    a
1   2.1    b
2   3.1    c
3   4.1    d
4   5.1    e
5   6.1    f
6   7.1    g
7   8.1    h
8   9.1    i
9  10.1    j

In [40]:
#single column
df2.loc[:,"col1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: col1, dtype: int64

In [50]:
#extracting multiple columns
df2.loc[0:5,["col1","col2","col3"]]

col1  col2 col3
0     1   1.1    a
1     2   2.1    b
2     3   3.1    c
3     4   4.1    d
4     5   5.1    e
5     6   6.1    f

In [65]:
df2.iloc[0:5,0:5]

col1  col2 col3
0     1   1.1    a
1     2   2.1    b
2     3   3.1    c
3     4   4.1    d
4     5   5.1    e

In [66]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    10 non-null     int64  
 1   col2    10 non-null     float64
 2   col3    10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [68]:
df2.index

RangeIndex(start=0, stop=10, step=1)

In [69]:
df2.shape

(10, 3)

In [70]:
df2.columns

Index(['col1', 'col2', 'col3'], dtype='object')

## Viewing data from DataFrame:
1. head()
2. tail()
3. sample()

In [72]:
df2.head()

col1  col2 col3
0     1   1.1    a
1     2   2.1    b
2     3   3.1    c
3     4   4.1    d
4     5   5.1    e

In [73]:
df2.head(3)

col1  col2 col3
0     1   1.1    a
1     2   2.1    b
2     3   3.1    c

In [74]:
df2.tail()

col1  col2 col3
5     6   6.1    f
6     7   7.1    g
7     8   8.1    h
8     9   9.1    i
9    10  10.1    j

In [75]:
df2.tail(8)

col1  col2 col3
2     3   3.1    c
3     4   4.1    d
4     5   5.1    e
5     6   6.1    f
6     7   7.1    g
7     8   8.1    h
8     9   9.1    i
9    10  10.1    j

In [76]:
df2.sample()

col1  col2 col3
2     3   3.1    c

In [77]:
df2.sample()

col1  col2 col3
1     2   2.1    b

In [78]:
df2.sample(2)

col1  col2 col3
8     9   9.1    i
1     2   2.1    b

In [79]:
 df2.describe()

col1      col2
count  10.00000  10.00000
mean    5.50000   5.60000
std     3.02765   3.02765
min     1.00000   1.10000
25%     3.25000   3.35000
50%     5.50000   5.60000
75%     7.75000   7.85000
max    10.00000  10.10000

In [80]:
df2=df2.rename(columns={"col1":"1st","col2":"2nd","col3":"3rd"})
df2

1st   2nd 3rd
0    1   1.1   a
1    2   2.1   b
2    3   3.1   c
3    4   4.1   d
4    5   5.1   e
5    6   6.1   f
6    7   7.1   g
7    8   8.1   h
8    9   9.1   i
9   10  10.1   j